apiVersion: v1
kind: Service
metadata:
  name: gateway-service # 다른 서비스와 이름 충돌을 피하기 위해 '-service' 접미사 추가를 권장합니다.
  labels:
    app: gateway
spec:
  # ✅ LoadBalancer에서 ClusterIP로 변경
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
