# ===================================================
# 13. 로그인/회원가입 프론트엔드 배포
# ===================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lee-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend-lee
  template:
    metadata:
      labels:
        app: frontend-lee
    spec:
      nodeSelector:
        agentpool: userpool
      containers:
        - name: frontend-lee-container
          image: kt16big.azurecr.io/frontend-lee:${IMAGE_TAG}
          ports:
            - containerPort: 9003
---
# ===================================================
# 14. 로그인/회원가입 프론트엔드 서비스
# ===================================================
apiVersion: v1
kind: Service
metadata:
  name: frontend-lee-service
spec:
  type: ClusterIP
  selector:
    app: frontend-lee
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003