# ===================================================
# 웹툰 챗봇 - 백엔드(FastAPI) 배포 - Lee Namespace
# ===================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-backend-deployment-lee
  namespace: lee
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: question-backend-lee
  template:
    metadata:
      labels:
        app: question-backend-lee
    spec:
      nodeSelector:
        agentpool: ragpool
      containers:
        - name: chatbot-backend-container
          image: kt16big.azurecr.io/chatbot-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: OPENAI_API_KEY
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1500m"
          livenessProbe:
            httpGet:
              path: /question-api/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /question-api/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
# ===================================================
# 웹툰 챗봇 - 백엔드 서비스 - Lee Namespace
# ===================================================
apiVersion: v1
kind: Service
metadata:
  name: question-backend-service-lee
  namespace: lee
spec:
  type: ClusterIP
  selector:
    app: question-backend-lee
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083