# ===================================================
# 24. 웹툰 하이라이트 - 프론트엔드(React) 배포
# ===================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtoon-hl-frontend-deployment-lee-2
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: webtoon-hl-frontend-lee-2
  template:
    metadata:
      labels:
        app: webtoon-hl-frontend-lee-2
    spec:
      nodeSelector:
        agentpool: userpool
      containers:
        - name: webtoon-hl-frontend-container-lee-2
          image: kt16big.azurecr.io/webtoon-hl-frontend-lee-2:${IMAGE_TAG}
          ports:
            - containerPort: 80
---
# ===================================================
# 25. 웹툰 하이라이트 - 프론트엔드 서비스
# ===================================================
apiVersion: v1
kind: Service
metadata:
  name: webtoon-hl-frontend-service-lee-2
spec:
  type: ClusterIP
  selector:
    app: webtoon-hl-frontend-lee-2
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 80