# ✅ [수정] user/src/main/resources/application.yml

# 서버 포트는 deployment.yaml에서 지정하므로 여기서 삭제하거나 주석 처리합니다.
# server:
#   port: 8081

spring:
  # 데이터베이스 설정을 최상위로 이동하여 항상 적용되도록 합니다.
  datasource:
    # 쿠버네티스 Secret의 환경변수 이름을 직접 참조합니다.
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
# Kafka 설정
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:kafka-service:9092}
          auto-create-topics: true
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:auth-service}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # ✅ [추가] Spring Mail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'mydefinary@gmail.com'
    password: '!Q2w3e4r'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# --- 프로필 구분선을 모두 제거 ---