# ===================================================
# 웹툰 대시보드 - 백엔드(FastAPI) 배포
# ===================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtoon-dashboard-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtoon-dashboard-backend
  template:
    metadata:
      labels:
        app: webtoon-dashboard-backend
    spec:
      # ✅ [수정] Pod가 'userpool'에서 실행되도록 강제합니다.
      nodeSelector:
        agentpool: userpool
      containers:
      - name: webtoon-dashboard-backend-container
        image: kt16big.azurecr.io/webtoon-dashboard-backend:latest
        ports:
        - containerPort: 8000
        workingDir: /app
        env:
        # 웹툰 대시보드에서 사용하는 환경변수들을 여기에 추가하세요
        # 예시:
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: api-keys-secret
        #       key: DATABASE_URL
---
# ===================================================
# 웹툰 대시보드 - 백엔드 서비스
# ===================================================
apiVersion: v1
kind: Service
metadata:
  name: webtoon-dashboard-backend-service
spec:
  type: ClusterIP
  selector:
    app: webtoon-dashboard-backend
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8000
---
# ===================================================
# 웹툰 대시보드 - 프론트엔드(React) 배포
# ===================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtoon-dashboard-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtoon-dashboard-frontend
  template:
    metadata:
      labels:
        app: webtoon-dashboard-frontend
    spec:
      # ✅ [수정] Pod가 'userpool'에서 실행되도록 강제합니다.
      nodeSelector:
        agentpool: userpool
      containers:
      - name: webtoon-dashboard-frontend-container
        image: kt16big.azurecr.io/webtoon-dashboard-frontend:latest
        ports:
        - containerPort: 80
        workingDir: /usr/share/nginx/html
---
# ===================================================
# 웹툰 대시보드 - 프론트엔드 서비스
# ===================================================
apiVersion: v1
kind: Service
metadata:
  name: webtoon-dashboard-frontend-service
spec:
  type: ClusterIP
  selector:
    app: webtoon-dashboard-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# ===================================================
# 웹툰 대시보드용 인그레스(Ingress) 규칙
# ===================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtoon-dashboard-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      # 웹툰 대시보드 FE
      - path: /webtoon-dashboard(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: webtoon-dashboard-frontend-service
            port:
              number: 80
      # 웹툰 대시보드 BE
      - path: /api/webtoon-dashboard(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: webtoon-dashboard-backend-service
            port:
              number: 8002