# 수정된 게이트웨이 설정 - 모든 프론트엔드 정적 자산 라우팅 포함
# 적용일: 2025-08-18
# 주요 변경사항: 
# 1. webtoon-hl-frontend 포트 3003 → 80 수정
# 2. 모든 프론트엔드 서비스에 정적 자산 전용 라우트 추가
# 3. 라우팅 우선순위 조정

server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://20.249.154.2"
            allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: false

      routes:
        # ===================================================
        # 1. 인증 서비스 - 공개 경로 (인증 불필요)
        # ===================================================
        - id: auth-public-routes
          uri: http://auth-backend-service-hoa:8080
          predicates:
            - Path=/api/auths/login, /api/auths/register, /api/auths/verify-code, /api/auths/resend-code, /api/auths/check-email, /api/auths/check-login-id, /api/auths/refresh, /api/auths/reset-password, /api/auths/health, /api/auths/save-password, /api/auths/test-login, /api/auths/safe-login, /api/auths/check-user/**
          filters:
            - StripPrefix=1
          order: 0

        # ===================================================
        # 2. 사용자 서비스 - 공개 경로 (인증 불필요)
        # ===================================================
        - id: user-public-routes
          uri: http://user-backend-service-hoa:8081
          predicates:
            - Path=/api/users/register, /api/users/check-email, /api/users/find-id, /api/users/health, /api/users/test-json, /api/users/test-complex
          filters:
            - StripPrefix=1
          order: 1

        # ===================================================
        # 3. 인증 서비스 - 보호된 경로 (인증 필요)
        # ===================================================
        - id: auth-secure-routes
          uri: http://auth-backend-service-hoa:8080
          predicates:
            - Path=/api/auths/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=1
          order: 2

        # ===================================================
        # 4. 사용자 서비스 - 보호된 경로 (인증 필요)
        # ===================================================
        - id: user-secure-routes
          uri: http://user-backend-service-hoa:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=1
          order: 3

        # ===================================================
        # 프론트엔드 서비스 라우팅 (실제 서비스 페이지)
        # ===================================================
        # ppl-gen 정적 자산 먼저 처리 
        - id: ppl-gen-assets
          uri: http://ppl-gen-frontend-service:80
          predicates:
            - Path=/ppl-gen/assets/**, /ppl-gen/static/**, /ppl-gen/*.js, /ppl-gen/*.css, /ppl-gen/*.png, /ppl-gen/*.jpg, /ppl-gen/*.svg
          filters:
            - StripPrefix=1
          order: 4

        - id: ppl-gen-frontend
          uri: http://ppl-gen-frontend-service:80
          predicates:
            - Path=/ppl-gen, /ppl-gen/**
          filters:
            - StripPrefix=1
          order: 5

        # goods-gen 정적 자산 먼저 처리
        - id: goods-gen-assets
          uri: http://goods-gen-frontend-service:80
          predicates:
            - Path=/goods-gen/assets/**, /goods-gen/static/**, /goods-gen/*.js, /goods-gen/*.css, /goods-gen/*.png, /goods-gen/*.jpg, /goods-gen/*.svg
          filters:
            - StripPrefix=1
          order: 5.5

        - id: goods-gen-frontend  
          uri: http://goods-gen-frontend-service:80
          predicates:
            - Path=/goods-gen, /goods-gen/**
          filters:
            - StripPrefix=1
          order: 6

        # webtoon-hl 정적 자산 먼저 처리
        - id: webtoon-hl-assets
          uri: http://webtoon-hl-frontend-service:80
          predicates:
            - Path=/webtoon-hl/assets/**, /webtoon-hl/static/**, /webtoon-hl/*.js, /webtoon-hl/*.css, /webtoon-hl/*.png, /webtoon-hl/*.jpg, /webtoon-hl/*.svg
          filters:
            - StripPrefix=1
          order: 6.5

        - id: webtoon-hl-frontend
          uri: http://webtoon-hl-frontend-service:80
          predicates:
            - Path=/webtoon-hl, /webtoon-hl/**
          filters:
            - StripPrefix=1
          order: 7

        # webtoon-dashboard 정적 자산 먼저 처리
        - id: webtoon-dashboard-assets
          uri: http://webtoon-dashboard-frontend-service:80
          predicates:
            - Path=/webtoon-dashboard/assets/**, /webtoon-dashboard/static/**, /webtoon-dashboard/*.js, /webtoon-dashboard/*.css, /webtoon-dashboard/*.png, /webtoon-dashboard/*.jpg, /webtoon-dashboard/*.svg
          filters:
            - StripPrefix=1
          order: 7.5

        - id: webtoon-dashboard-frontend
          uri: http://webtoon-dashboard-frontend-service:80
          predicates:
            - Path=/webtoon-dashboard, /webtoon-dashboard/**
          filters:
            - StripPrefix=1
          order: 8

        # board 정적 자산 먼저 처리
        - id: board-assets
          uri: http://board-frontend-service:80
          predicates:
            - Path=/board/assets/**, /board/static/**, /board/*.js, /board/*.css, /board/*.png, /board/*.jpg, /board/*.svg
          filters:
            - StripPrefix=1
          order: 8.5

        - id: board-frontend
          uri: http://board-frontend-service:80
          predicates:
            - Path=/board, /board/**
          filters:
            - StripPrefix=1
          order: 9

        # ===================================================
        # 메인 프론트엔드 정적 자산 먼저 처리
        # ===================================================
        - id: main-frontend-assets
          uri: http://auth-frontend-service-hoa:80
          predicates:
            - Path=/assets/**, /static/**, /*.js, /*.css, /*.png, /*.jpg, /*.svg, /favicon.ico, /vite.svg
          order: 90

        # ===================================================
        # 메인 프론트엔드 (기본 경로들만) - 가장 낮은 우선순위
        # ===================================================
        - id: main-frontend
          uri: http://auth-frontend-service-hoa:80
          predicates:
            - Path=/, /login, /register, /email-verification, /find-id, /find-password, /dashboard, /mypage, /faq
          order: 100

        # ===================================================
        # PPL & Goods Generation APIs - 공개 경로 (인증 불필요)
        # ===================================================
        - id: ppl-gen-service
          uri: http://ppl-gen-backend-service:8000
          predicates:
            - Path=/api/ppl-gen/**
          filters:
            - StripPrefix=2
          order: 10

        - id: goods-gen-service
          uri: http://goods-gen-backend-service:8001
          predicates:
            - Path=/api/goods-gen/**
          filters:
            - StripPrefix=2
          order: 11

        - id: webtoon-dashboard-service
          uri: http://webtoon-dashboard-backend-service:8002
          predicates:
            - Path=/api/webtoon/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
          order: 12

        - id: webtoon-hl-service
          uri: http://webtoon-hl-backend-service:8003
          predicates:
            - Path=/api/webtoon-hl/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
          order: 13

        - id: board-service
          uri: http://board-backend-service:8082
          predicates:
            - Path=/api/board/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
          order: 14

        - id: chatbot-service
          uri: http://chatbot-backend-service:8080
          predicates:
            - Path=/api/chatbot/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
          order: 15

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-here-make-it-long-and-secure-at-least-32-characters}