# deployment/auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # ✅ 이름 수정
  name: auth-backend-deployment-hoa
spec:
  replicas: 1
  selector:
    matchLabels:
      # ✅ 이름 수정
      app: auth-backend-hoa
  template:
    metadata:
      labels:
        # ✅ 이름 수정
        app: auth-backend-hoa
    spec:
      nodeSelector:
        agentpool: userpool
      containers:
        # ✅ 이름 수정
        - name: auth-backend-container-hoa
          image: kt16big.azurecr.io/auth-backend-hoa:$latest
          ports:
            - containerPort: 8080
          env:
            - name: jwt.secret
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: JWT_SECRET_KEY
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: DB_URL
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: DB_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: DB_PASSWORD
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: spring.mail.host
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: spring.mail.username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: spring.mail.password
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: spring.mail.port
            # 다른 필요한 환경변수들도 추가
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  # ✅ 이름 수정
  name: auth-backend-service-hoa
spec:
  type: ClusterIP
  selector:
    # ✅ 이름 수정 (위의 Deployment app 레이블과 일치해야 함)
    app: auth-backend-hoa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080