# ✅ [수정] auth/src/main/resources/application.yml

spring:
  datasource:
    # 쿠버네티스 Secret의 환경변수 이름을 직접 참조합니다.
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  # 쿠버네티스 Secret의 환경변수 이름을 직접 참조합니다.
  secret: ${jwt.secret}

logging:
  level:
    org.hibernate.SQL: debug