# auth application.yml
server:
  port: 8080

spring:
  datasource:
    # Azure MySQL 연결 설정 (SSL 및 타임존 설정 포함)
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://kt16sql.mysql.database.azure.com:3306/kt16sql?useSSL=true&requireSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:kt16jo}
    password: ${SPRING_DATASOURCE_PASSWORD:kt!6jojo}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Kafka 설정
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:kafka-service:9092}
          auto-create-topics: true
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:auth-service}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: ${JWT_SECRET:your-default-jwt-secret}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.cloud.stream: debug
    org.apache.kafka: info
    service: debug