# 워크플로우 이름 (예: 'CI/CD for Auth Service')
name: 'CI/CD for Auth Service'

on:
  push:
    branches: [ "login-cicd" ] # CI/CD를 적용할 브랜치
    paths:
      - 'auth/**'                     # 1. 해당 서비스의 소스코드 경로
      - '.github/workflows/auth-cicd.yml' # 2. 워크플로우 파일 자신
      - 'all-deployment.yaml'         # 3. 공용 배포 파일

# 워크플로우 전체에서 사용할 환경 변수
env:
  ACR_NAME: "kt16big"
  AKS_CLUSTER_NAME: "kt16big-aks"
  AKS_RESOURCE_GROUP: "kt16big"
  # --- 서비스별로 이 부분만 수정 ---
  IMAGE_NAME: "auth-backend"
  WORKING_DIR: "auth"
  DEPLOYMENT_NAME: "auth-backend-deployment"
  MANIFEST_FILE: "all-deployment.yaml"

jobs:
  build-and-push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIR }}
          file: ${{ env.WORKING_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-aks:
    # ✅ build-and-push-to-acr 잡의 성공 여부와 관계없이 항상 실행
    # (all-deployment.yaml만 변경되어도 배포는 해야 하므로)
    needs: build-and-push-to-acr
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          # build 잡이 성공적으로 실행된 경우(새 이미지가 만들어진 경우)에만 이미지 태그를 교체
          if [ "${{ needs.build-and-push-to-acr.result }}" == "success" ]; then
            echo "New image detected. Updating image tag in manifest..."
            sed -i "s|${{ env.IMAGE_NAME }}:\${IMAGE_TAG}|${{ env.IMAGE_NAME }}:${{ github.sha }}|g" ${{ env.MANIFEST_FILE }}
          else
            echo "No new image built. Applying manifest as is."
          fi

          # 수정되었거나, 혹은 그대로인 매니페스트 파일을 AKS에 적용
          kubectl apply -f ${{ env.MANIFEST_FILE }}
