name: Chatbot Frontend CI/CD

on:
  push:
    branches: [ "chatbot" ]
    paths:
      - "chatbot/frontend/**"
      - "deployments/chatbot-frontend-deployment.yaml"
      - ".github/workflows/chatbot-frontend-cicd.yaml"
  pull_request:
    branches: [ "chatbot" ]
    paths:
      - "chatbot/frontend/**"

env:
  ACR_NAME: "kt16big"
  IMAGE_NAME: "chatbot-backend"
  WORKING_DIR: "chatbot/backend"
  AKS_CLUSTER_NAME: "kt16big-aks"
  AKS_RESOURCE_GROUP: "kt16big"
  DEPLOYMENT_FILE: "deployments/chatbot-backend.yaml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Lint & build
        run: |
          npm run build --if-present
          npm run lint --if-present
          # 테스트 러너가 있으면 활성화
          # npm test -- --ci --reporters=default

  docker-publish:
    needs: build-and-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-frontend:sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: docker-publish
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig from secret
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Apply manifests
        run: |
          kubectl apply -f deployments/chatbot-frontend-deployment.yaml

      - name: Update image to current SHA
        run: |
          kubectl set image deployment/chatbot-frontend \
            frontend=ghcr.io/${{ github.repository }}-frontend:sha-${{ github.sha }}
          kubectl rollout status deployment/chatbot-frontend --timeout=120s
