# .github/workflows/goods-gen-fe-cicd.yml

name: 'CI/CD for GOODS-GEN Frontend'

on:
  push:
    branches: [ "img-gen-cicd" ]
    paths:
      - 'goods-gen-react/frontend/**'
      - '.github/workflows/goods-gen-fe-cicd.yml'
  pull_request:
    branches: [ "img-gen-cicd" ]
    paths:
      - 'goods-gen-react/frontend/**'
      - '.github/workflows/goods-gen-fe-cicd.yml'


env:
  ACR_NAME: "kt16big"
  IMAGE_NAME: "goods-gen-frontend"
  WORKING_DIR: "goods-gen-react/frontend"
  AKS_CLUSTER_NAME: "kt16big-aks"
  AKS_RESOURCE_GROUP: "kt16big"

jobs:
  build-and-push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIR }}
          file: ${{ env.WORKING_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push-to-acr
    steps:
      # 1. 리포지토리 코드 가져오기 (all-deployment.yaml 파일을 읽기 위해 필요)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
      # ✅ [수정] kubectl을 사용하여 특정 Deployment의 이미지만 교체
      - name: Deploy to AKS by setting image
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
            ppl-gen-frontend-container=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}