name: CI/CD for Webtoon Highlight Backend

on:
  push:
    branches: [ webtoon-highlight ]     # 원하는 브랜치로 변경 가능
    paths:
      - "backend/**"
      - "deployments/webtoon-highlight-backend-deployment.yaml"
      - ".github/workflows/webtoon-hl-be-cicd.yml"
  workflow_dispatch: {}                  # 수동 실행 버튼

concurrency:
  group: webtoon-hl-be-${{ github.ref }}
  cancel-in-progress: false

env:
  ACR_NAME: "kt16big"
  IMAGE_NAME: "webtoon-hl-backend"
  WORKING_DIR: "backend"
  AKS_CLUSTER_NAME: "kt16big-aks"
  AKS_RESOURCE_GROUP: "kt16big"
  DEPLOYMENT_NAME: "webtoon-hl-backend-deployment"
  CONTAINER_NAME: "webtoon-hl-backend-container"
  K8S_NAMESPACE: "default"              # 네임스페이스 다르면 바꾸기

jobs:
  build-and-push-to-acr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write                   # azure/login OIDC 필요
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIR }}
          file: ${{ env.WORKING_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push-to-acr
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Apply manifest if deployment not found
        run: |
          if ! kubectl -n $K8S_NAMESPACE get deploy $DEPLOYMENT_NAME >/dev/null 2>&1; then
            kubectl -n $K8S_NAMESPACE apply -f deployments/webtoon-highlight-backend-deployment.yaml
          fi

      - name: Rollout by updating image
        run: |
          kubectl -n $K8S_NAMESPACE set image deployment/$DEPLOYMENT_NAME \
            $CONTAINER_NAME=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          kubectl -n $K8S_NAMESPACE rollout status deployment/$DEPLOYMENT_NAME --timeout=180s
